apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 111868661773.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newName: 111868661773.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
  newTag: a5b90c2d
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
